name: ContinuousContribution

# on:
#   schedule:
#     - cron: '*/30 * * * *'  # Runs every 5 minutes

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Run JavaScript Date formatting script
      #   run: |
      #     echo "const date = new Date();"
      #     echo "const day = String(date.getDate()).padStart(2, '0');"
      #     echo "const month = String(date.getMonth() + 1).padStart(2, '0');"
      #     echo "const year = date.getFullYear();"
      #     echo "const hours = date.getHours();"
      #     echo "const minutes = String(date.getMinutes()).padStart(2, '0');"
      #     echo "const seconds = String(date.getSeconds()).padStart(2, '0');"
      #     echo "const ampm = hours >= 12 ? 'PM' : 'AM';"
      #     echo "const formattedHours = hours % 12 || 12;"
      #     echo "console.log(`${day}/${month}/${year} ${formattedHours}:${minutes}:${seconds} ${ampm}`);"
      #     node -e "$(cat)"

      - name: Update Time in README
        run: |
          sed -i "s/Last updated: .*/Last updated: $(date +'%d/%m/%Y %I:%M:%S %p')/" README.md

      - name: Commit New Time with auto commit
        run:  |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Released with new time"
          git push origin main
          echo "Committed release"

      - name: Create tag
        run: |
          TAG_NAME=$(date +'%Y%m%d%H%M%S')
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "Created tag $TAG_NAME"