name: ContinuousContribution

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  ContinuousContribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Required for using PAT

      - name: Set up Git
        run: |
          git config --local user.name "joblessgod"
          git config --local user.email "iamjoblessgod@gmail.com"

      - name: Update README.md with contribution count
        run: |
          COUNT=$(grep -oP 'contribution while offline: \K\d+' README.md || echo 0)
          NEW_COUNT=$((COUNT + 1))
          sed -i 's/contribution while offline: .*/contribution while offline: '"$NEW_COUNT"'/g' README.md || echo "contribution while offline: 1" >> README.md
          echo "Last updated: $(date)" >> README.md  # Ensures file change

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git add README.md
          git commit -m "Update contribution count to $NEW_COUNT" --allow-empty
          git push https://x-access-token:${PAT}@github.com/joblessgod/joblessgod.git main
