name: ContinuousContribution

# on:
#   schedule:
#     - cron: '*/30 * * * *'  # Runs every 5 minutes

on:
  push:
    branches:
      - main

jobs:
  updateReadmeTime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update Time in README
        run: |
          export TZ="Asia/Kathmandu"
          DATE=$(date +'%d/%m/%Y %I:%M:%S %p')
          sed -i "s|Last updated: .*|Last updated: $DATE|" README.md
          echo "Updated README with current date and time: $DATE"

      - name: Update Commit Count in README
        run: |
          COMMIT_COUNT=$(git rev-list --count --all)
          sed -i "s|Total commits(while offline): .*|Total commits(while offline): $COMMIT_COUNT|" README.md
          echo "Updated README with commit count: $COMMIT_COUNT"

      - name: Commit New Time and Commit Count with auto commit
        run:  |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Updated README with new time and commit count"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/joblessgod/joblessgod.git main
          echo "Committed release"

      - name: Create tag
        run: |
          TAG_NAME=$(date +'%Y-%m-%d_%H-%M-%S')
          git tag $TAG_NAME
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/joblessgod/joblessgod.git $TAG_NAME
          echo "Created tag $TAG_NAME"