name: ContinuousContribution

on:
  schedule:
    - cron: '*/3 * * * *'  # Runs every 3 minutes

jobs:
  ContinuousContribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Required for PAT authentication

      - name: Set up Git
        run: |
          git config --global user.name "joblessgod"
          git config --global user.email "iamjoblessgod@gmail.com"

      - name: Update README.md with contribution count
        run: |
          git pull origin main  # Ensure you're working with the latest version
          
          # Check if the line "contribution while offline:" exists
          COUNT=$(grep -oP 'contribution while offline: \K\d+' README.md || echo 0)
          NEW_COUNT=$((COUNT + 1))
          
          # Update or append the contribution line
          if grep -q 'contribution while offline:' README.md; then
            sed -i 's/contribution while offline: .*/contribution while offline: '"$NEW_COUNT"'/g' README.md
          else
            echo "contribution while offline: $NEW_COUNT" >> README.md
          fi

          # Append last updated timestamp
          echo "Last updated: $(date)" >> README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update contribution count to $NEW_COUNT" --allow-empty

      - name: Push changes directly to the main branch
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git push https://x-access-token:${PAT}@github.com/joblessgod/joblessgod.git HEAD:main
